//! Generates a systemd service override that adds `ReadWriteDirectories` for
//! customer certificate paths, allowing writes through `ProtectSystem=full`.

use std::collections::BTreeSet;
use std::io;
use std::path::{Path, PathBuf};

use super::types::AcmConfig;
use crate::constants::{
    ACM_SERVICE_OVERRIDE_DIR, ACM_SERVICE_OVERRIDE_FILE, PROVIDER_HOME_DIR, PROVIDER_NAME,
};
use crate::filesystem::{FileSystem, RealFileSystem};

/// Generates and installs the systemd drop-in override from ACM configuration.
///
/// Extracts unique parent directories from all configured certificate paths and
/// writes a drop-in that adds them to `ReadWriteDirectories`.
pub fn generate_and_install(acm_config: &AcmConfig) -> io::Result<()> {
    let content = generate_override_content(acm_config);
    let fs = RealFileSystem;
    let override_dir = Path::new(ACM_SERVICE_OVERRIDE_DIR);
    std::fs::create_dir_all(override_dir)?;
    let tmp_path = fs.write_string_to_temp(override_dir, &content)?;
    if let Err(e) = fs.atomic_rename(&tmp_path, &override_path()) {
        let _ = fs.remove_file(&tmp_path);
        return Err(e);
    }
    Ok(())
}

/// Generates the content of the systemd drop-in override file.
fn generate_override_content(acm_config: &AcmConfig) -> String {
    let mut dirs: BTreeSet<&Path> = BTreeSet::new();

    for cert in acm_config.certificates.values() {
        if let Some(parent) = cert.certificate_path.parent() {
            dirs.insert(parent);
        }
        if let Some(parent) = cert.private_key_path.parent() {
            dirs.insert(parent);
        }
        if let Some(ref chain) = cert.chain_path {
            if let Some(parent) = chain.parent() {
                dirs.insert(parent);
            }
        }
    }

    // Always include the log directory
    let log_dir = Path::new(PROVIDER_HOME_DIR).join("logs");
    dirs.insert(log_dir.as_path());

    let paths_str: String = dirs
        .iter()
        .map(|p| p.to_string_lossy().replace(' ', "\\x20"))
        .collect::<Vec<_>>()
        .join(" ");

    format!(
        "# Auto-generated by {PROVIDER_NAME} setup-config-based-permissions\n\
         # DO NOT EDIT MANUALLY\n\
         [Service]\n\
         ReadWriteDirectories={paths_str}\n"
    )
}

/// Returns the full path to the generated override file.
pub fn override_path() -> PathBuf {
    Path::new(ACM_SERVICE_OVERRIDE_DIR).join(ACM_SERVICE_OVERRIDE_FILE)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::types::CertificateConfig;
    use std::collections::HashMap;

    fn make_config(paths: &[(&str, &str, Option<&str>)]) -> AcmConfig {
        let mut certificates = HashMap::new();
        for (i, (cert, key, chain)) in paths.iter().enumerate() {
            certificates.insert(
                format!("arn:aws:acm:us-west-2:123456789012:certificate/test-{i}"),
                CertificateConfig {
                    certificate_arn: format!(
                        "arn:aws:acm:us-west-2:123456789012:certificate/test-{i}"
                    ),
                    certificate_path: PathBuf::from(cert),
                    private_key_path: PathBuf::from(key),
                    chain_path: chain.map(PathBuf::from),
                    refresh_command: Some("/bin/echo reload".to_string()),
                    role_arn: "arn:aws:iam::123456789012:role/Test".to_string(),
                    cert_and_chain_permission: None,
                    key_permission: None,
                },
            );
        }
        AcmConfig {
            enabled: true,
            certificates,
        }
    }

    #[test]
    fn test_generates_override_with_cert_paths() {
        let config = make_config(&[(
            "/etc/ssl/certs/server.crt",
            "/etc/ssl/private/server.key",
            None,
        )]);
        let content = generate_override_content(&config);
        assert!(content.contains("ReadWriteDirectories="));
        assert!(content.contains("/etc/ssl/certs"));
        assert!(content.contains("/etc/ssl/private"));
        assert!(content.contains("/opt/aws/workload-credentials-provider/logs"));
    }

    #[test]
    fn test_deduplicates_paths() {
        let config = make_config(&[(
            "/opt/certs/server.crt",
            "/opt/certs/server.key",
            Some("/opt/certs/chain.pem"),
        )]);
        let content = generate_override_content(&config);
        // /opt/certs should appear only once
        let count = content.matches("/opt/certs").count();
        assert_eq!(count, 1);
    }

    #[test]
    fn test_multiple_certificates_different_dirs() {
        let config = make_config(&[
            ("/etc/nginx/certs/a.crt", "/etc/nginx/certs/a.key", None),
            ("/etc/ssl/certs/b.crt", "/etc/ssl/private/b.key", None),
        ]);
        let content = generate_override_content(&config);
        assert!(content.contains("/etc/nginx/certs"));
        assert!(content.contains("/etc/ssl/certs"));
        assert!(content.contains("/etc/ssl/private"));
    }
}
