//! Concrete [`RefreshExecutor`] implementation that runs the user-configured
//! `refresh_command` after a certificate is updated.
//!
//! Platform behavior:
//! - Unix: `sudo <program> <args...>` — the command is exec'd directly so that
//!   it matches the sudoers entry generated by the install script.
//! - Windows: `schtasks /Run` to trigger a pre-registered scheduled task, then
//!   polls via PowerShell `Get-ScheduledTask`/`Get-ScheduledTaskInfo` until the
//!   task completes or times out. The scheduled task name is derived from the
//!   certificate ARN.
//!
//! This is invoked by [`CertificateTask`](crate::certificate_task::CertificateTask)
//! as the final step of the refresh workflow (export → store → execute).
//! Failures are propagated to the caller so they are recorded and retried.

use crate::traits::RefreshExecutor;
use log::{error, info};
use tokio::process::Command;
use tokio::time::{timeout, Duration};

/// Maximum time a refresh command is allowed to run before being considered hung.
const REFRESH_COMMAND_TIMEOUT: Duration = Duration::from_mins(15);

/// Polling interval when waiting for a Windows scheduled task to complete.
#[cfg(windows)]
const SCHTASK_POLL_INTERVAL: Duration = Duration::from_secs(2);

/// Production implementation of [`RefreshExecutor`].
pub(crate) struct DefaultRefreshExecutor;

impl RefreshExecutor for DefaultRefreshExecutor {
    async fn execute(&self, command: &str, certificate_arn: &str) -> Result<(), std::io::Error> {
        info!("Executing refresh command for {}", certificate_arn);

        #[cfg(unix)]
        execute_unix(command, certificate_arn).await?;

        #[cfg(windows)]
        execute_windows(certificate_arn).await?;

        info!("Refresh command succeeded for {}", certificate_arn);
        Ok(())
    }
}

/// Runs the command via `sudo` with direct exec.
///
/// The install script generates a sudoers entry that matches the exact command,
/// so we must invoke `sudo <program> <args...>`.
#[cfg(unix)]
async fn execute_unix(command: &str, certificate_arn: &str) -> Result<(), std::io::Error> {
    let args: Vec<&str> = command.split_whitespace().collect();
    let mut child = Command::new("sudo")
        .arg("-n")
        .args(&args)
        .kill_on_drop(true)
        .spawn()?;

    let status = timeout(REFRESH_COMMAND_TIMEOUT, child.wait())
        .await
        .map_err(|_| {
            let _ = child.start_kill();
            std::io::Error::new(
                std::io::ErrorKind::TimedOut,
                format!("refresh command timed out after {REFRESH_COMMAND_TIMEOUT:?}"),
            )
        })??;

    if !status.success() {
        error!(
            "Refresh command exited with {} for {}",
            status, certificate_arn
        );
        return Err(std::io::Error::other(format!(
            "command exited with {status}"
        )));
    }

    Ok(())
}

/// Triggers a pre-registered scheduled task and polls until completion.
///
/// On Windows, the install script registers the refresh command as a scheduled
/// task running as SYSTEM. The provider triggers it by ARN-derived task name
/// rather than running the command directly.
#[cfg(windows)]
async fn execute_windows(certificate_arn: &str) -> Result<(), std::io::Error> {
    let task_name = scheduled_task_name(certificate_arn);

    // Snapshot "LastRunTime" before triggering, so we can detect completion
    // even if the task finishes before the first poll.
    let pre_status = query_task_status(&task_name).await?;

    let run_output = Command::new("schtasks")
        .args(["/Run", "/TN", &task_name])
        .output()
        .await?;

    if !run_output.status.success() {
        let stderr = String::from_utf8_lossy(&run_output.stderr);
        error!("schtasks /Run failed for {}: {}", certificate_arn, stderr);
        return Err(std::io::Error::other(format!(
            "schtasks /Run failed: {stderr}"
        )));
    }

    poll_scheduled_task(&task_name, certificate_arn, &pre_status.last_run_time).await
}

/// Polls task status until the task completes or times out.
///
/// Completion is detected by comparing "LastRunTime" against the pre-run
/// snapshot, which avoids a race where the task starts and finishes between
/// polls (never observed in "Running" state).
#[cfg(windows)]
async fn poll_scheduled_task(
    task_name: &str,
    certificate_arn: &str,
    pre_run_time: &str,
) -> Result<(), std::io::Error> {
    let deadline = tokio::time::Instant::now() + REFRESH_COMMAND_TIMEOUT;

    loop {
        tokio::time::sleep(SCHTASK_POLL_INTERVAL).await;

        let remaining = deadline.saturating_duration_since(tokio::time::Instant::now());
        if remaining.is_zero() {
            let _ = Command::new("schtasks")
                .args(["/End", "/TN", task_name])
                .output()
                .await;
            return Err(timeout_error());
        }

        let status = match timeout(remaining, query_task_status(task_name)).await {
            Ok(result) => result?,
            Err(_) => {
                let _ = Command::new("schtasks")
                    .args(["/End", "/TN", task_name])
                    .output()
                    .await;
                return Err(timeout_error());
            }
        };

        // Still running or "LastRunTime" hasn't changed — keep polling.
        if status.state == "Running" || status.last_run_time == pre_run_time {
            continue;
        }

        // Task completed — check result: "0" = success.
        if status.last_task_result != "0" {
            error!(
                "Scheduled task {} failed for {}",
                task_name, certificate_arn
            );
            return Err(std::io::Error::other(format!(
                "scheduled task {task_name} failed"
            )));
        }

        return Ok(());
    }
}

/// Status fields returned by [`query_task_status`].
#[cfg(windows)]
struct TaskStatus {
    state: String,
    last_run_time: String,
    last_task_result: String,
}

/// Queries scheduled task status via PowerShell's `Get-ScheduledTask` and
/// `Get-ScheduledTaskInfo` cmdlets, which return locale-independent values.
///
/// Output is a single pipe-delimited line: `State|LastRunTime|LastTaskResult`
/// e.g. `Ready|4/27/2026 9:00:00 AM|0`
#[cfg(windows)]
async fn query_task_status(task_name: &str) -> Result<TaskStatus, std::io::Error> {
    let ps_command = format!(
        "$t = Get-ScheduledTask -TaskName '{task_name}';\
         $i = Get-ScheduledTaskInfo -TaskName '{task_name}';\
         Write-Output \"$($t.State)|$($i.LastRunTime)|$($i.LastTaskResult)\""
    );

    let output = Command::new("powershell")
        .args(["-NoProfile", "-NonInteractive", "-Command", &ps_command])
        .output()
        .await?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(std::io::Error::other(format!(
            "PowerShell query failed: {stderr}"
        )));
    }

    parse_task_status(&String::from_utf8_lossy(&output.stdout))
}

/// Parses the pipe-delimited `State|LastRunTime|LastTaskResult` output from
/// the PowerShell query into a [`TaskStatus`].
#[cfg(windows)]
fn parse_task_status(output: &str) -> Result<TaskStatus, std::io::Error> {
    let line = output.trim();
    let parts: Vec<&str> = line.splitn(3, '|').collect();
    if parts.len() != 3 {
        return Err(std::io::Error::other(format!(
            "unexpected task status output: {line}"
        )));
    }
    Ok(TaskStatus {
        state: parts[0].to_string(),
        last_run_time: parts[1].to_string(),
        last_task_result: parts[2].to_string(),
    })
}

#[cfg(windows)]
fn timeout_error() -> std::io::Error {
    std::io::Error::new(
        std::io::ErrorKind::TimedOut,
        format!("scheduled task timed out after {REFRESH_COMMAND_TIMEOUT:?}"),
    )
}

/// Derives the Windows scheduled task name from a certificate ARN.
///
/// Replaces any character that isn't alphanumeric or a hyphen with `-`,
/// matching the PowerShell install script's `[^a-zA-Z0-9\-]` regex.
/// Example: `arn:aws:acm:us-east-1:123456789012:certificate/abc`
///       → `AWSWorkloadCredentialsProvider-Reload-arn-aws-acm-us-east-1-123456789012-certificate-abc`
#[cfg(windows)]
pub fn scheduled_task_name(certificate_arn: &str) -> String {
    let sanitized: String = certificate_arn
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '-' {
                c
            } else {
                '-'
            }
        })
        .collect();
    format!("AWSWorkloadCredentialsProvider-Reload-{sanitized}")
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Tests for execute_unix, which runs commands via sudo.
    ///
    /// These require passwordless sudo (e.g. CI with NOPASSWD). Gated behind
    /// `#[ignore]` — run with `cargo test -- --ignored`.
    #[cfg(unix)]
    mod unix_tests {
        use super::*;

        #[tokio::test]
        #[ignore]
        async fn execute_via_trait() {
            let executor = DefaultRefreshExecutor;
            assert!(executor
                .execute("/bin/echo hello", "arn:test")
                .await
                .is_ok());
        }

        #[tokio::test]
        #[ignore]
        async fn successful_command() {
            let result = execute_unix("/bin/echo hello", "arn:test").await;
            assert!(result.is_ok());
        }

        #[tokio::test]
        #[ignore]
        async fn failed_command_returns_error() {
            let result = execute_unix("/bin/false", "arn:test").await;
            assert!(result.is_err());
            let err = result.unwrap_err();
            assert!(err.to_string().contains("exit"), "{}", err);
        }

        #[tokio::test]
        #[ignore]
        async fn invalid_command_returns_error() {
            let result = execute_unix("/nonexistent_binary_12345", "arn:test").await;
            assert!(result.is_err());
        }

        #[tokio::test(start_paused = true)]
        #[ignore]
        async fn command_times_out() {
            let handle =
                tokio::spawn(async move { execute_unix("/bin/sleep 600", "arn:test").await });
            tokio::time::advance(REFRESH_COMMAND_TIMEOUT).await;
            let err = handle.await.unwrap().unwrap_err();
            assert_eq!(err.kind(), std::io::ErrorKind::TimedOut);
        }
    }

    #[cfg(windows)]
    mod windows_tests {
        use super::*;

        #[test]
        fn scheduled_task_name_sanitizes_arn() {
            assert_eq!(
                scheduled_task_name("arn:aws:acm:us-east-1:123456789012:certificate/12345678-1234-1234-1234-123456789012"),
                "AWSWorkloadCredentialsProvider-Reload-arn-aws-acm-us-east-1-123456789012-certificate-12345678-1234-1234-1234-123456789012"
            );
        }

        #[test]
        fn parse_task_status_success() {
            let status = parse_task_status("Ready|4/27/2026 9:00:00 AM|0\n").unwrap();
            assert_eq!(status.state, "Ready");
            assert_eq!(status.last_run_time, "4/27/2026 9:00:00 AM");
            assert_eq!(status.last_task_result, "0");
        }

        #[test]
        fn parse_task_status_nonzero_result() {
            let status = parse_task_status("Ready|4/27/2026 9:00:00 AM|1").unwrap();
            assert_eq!(status.last_task_result, "1");
        }

        #[test]
        fn parse_task_status_running() {
            let status = parse_task_status("Running|4/27/2026 9:00:00 AM|267009").unwrap();
            assert_eq!(status.state, "Running");
        }

        #[test]
        fn parse_task_status_empty_input() {
            assert!(parse_task_status("").is_err());
        }

        #[test]
        fn parse_task_status_malformed_input() {
            assert!(parse_task_status("Ready|missing_field").is_err());
        }

        #[test]
        fn timeout_error_has_correct_kind_and_message() {
            let error = timeout_error();
            assert_eq!(error.kind(), std::io::ErrorKind::TimedOut);
            assert!(error.to_string().contains("scheduled task timed out"));
        }
    }
}
