#!/bin/bash -e

PATH=/bin:/usr/bin:/sbin:/usr/sbin
TOKENFILE=/var/run/awssmatoken
TOKENGROUP=awssmatokenreader
case "$1" in
    start)
        echo -e "Initializing SMA SSRF token"
        touch ${TOKENFILE}
        chgrp ${TOKENGROUP} ${TOKENFILE}
        chmod 640 ${TOKENFILE}
        dd if=/dev/urandom bs=32 count=1 2>/dev/null \
            | sha256sum -b \
            | cut -f1 -d' ' \
        > ${TOKENFILE}
    ;;
    stop)
        echo -e "Clearing SMA SSRF token"
        rm -f ${TOKENFILE}
    ;;
esac

exit 0
