#!/bin/bash -e

PATH=/bin:/usr/bin:/sbin:/usr/sbin # Use a safe path

AGENTTARGETDIR=/opt/aws/secretsmanageragent
AGENTSOURCEDIR=../../target/release
AGENTBIN=aws_secretsmanager_agent
TOKENGROUP=awssmatokenreader
AGENTUSER=awssmauser
TOKENSCRIPT=awssmaseedtoken
AGENTSCRIPT=awssmastartup

SYSTEMDFILES=/etc/systemd/system

if [ `id -u` -ne 0 ]; then
    echo "This script must be run as root" >&2
    exit 1
fi

if [ ! -r ${TOKENSCRIPT} ]; then
    echo "Can not read ${TOKENSCRIPT}" >&2
    exit 1
fi

if [ ! -r ${AGENTSOURCEDIR}/${AGENTBIN} ]; then
    echo "Can not read ${AGENTBIN}" >&2
    exit 1
fi

groupadd -f ${TOKENGROUP}
useradd -r -m -g ${TOKENGROUP} -d ${AGENTTARGETDIR} ${AGENTUSER} || true
chmod 755 ${AGENTTARGETDIR}

install -D -T -m 755 ${AGENTSOURCEDIR}/${AGENTBIN} ${AGENTTARGETDIR}/bin/${AGENTBIN}
install -D -T -m 755 ${TOKENSCRIPT} ${AGENTTARGETDIR}/bin/${TOKENSCRIPT}
chown -R ${AGENTUSER} ${AGENTTARGETDIR}
install -T -m 755 ${TOKENSCRIPT}.service ${SYSTEMDFILES}/${TOKENSCRIPT}.service 
install -T -m 755 ${AGENTSCRIPT}.service ${SYSTEMDFILES}/${AGENTSCRIPT}.service

systemctl enable ${TOKENSCRIPT}
systemctl start ${TOKENSCRIPT}

systemctl enable ${AGENTSCRIPT}
systemctl start ${AGENTSCRIPT}

exit 0
