#!/bin/bash -x

if [ `id -u` -ne 0 ]; then
    echo "This script must be run as root" >&2
    exit 1
fi


AGENTDIR=/opt/aws/secretsmanageragent
TOKENGROUP=awssmatokenreader
AGENTUSER=awssmauser
TOKENSCRIPT=awssmaseedtoken
AGENTSCRIPT=awssmastartup

systemctl stop awssmastartup
systemctl disable awssmastartup
systemctl stop awssmaseedtoken
systemctl disable awssmaseedtoken
rm -f /etc/systemd/system/${TOKENSCRIPT}.service /etc/systemd/system/${AGENTSCRIPT}.service

rm -rf ${AGENTDIR}
userdel -r ${AGENTUSER}
groupdel ${TOKENGROUP}
